version: 0.2

phases:
  install:
    runtime-versions:
      - python: 3.7
  pre_build:
    commands:
      - python -m unittest discover tests
      - sam validate
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --template template.yml --s3-bucket $S3_BUCKET --output-template-file packaged-template.yml

artifacts:
  files:
    - packaged-template.yml
