version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python -m unittest discover tests
      - sam validate
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --template template.yml --s3-bucket ${ARTIFACT_BUCKET} --kms-key-id ${CODEBUILD_KMS_KEY_ID} --output-template-file packaged.yml

artifacts:
  files:
    - packaged.yml
